### ISSUE TITLE
Something wrong with board searching

### ISSUE THREAD

**Issue by fauxparse** [soundasleep/rboggle#3]
I didn't get a score for SQUAT on this board:
![image](https://cloud.githubusercontent.com/assets/530/9266474/9b9f7c66-4295-11e5-926f-3e5d9a0aef8b.png)

**Comment by soundasleep** [comment]
Fixed in https://github.com/soundasleep/rboggle/commit/41893357e0ef9a3cf5a7cc2910dfe2cb035d8cb2
